### ISSUE TITLE
Hook para o Contact form 7

### ISSUE THREAD

**Issue by augustoms** [ResultadosDigitais/rdstation-wp#2]
Olá pessoal,
obrigado pelo plugin que facilitou muito a integração dos meus forms com a plataforma RD!

Apenas uma observação:
Nos testes iniciais (apenas ativando o plugin e criando as integrações), percebi que nenhum lead era gerado na RD Station. Ao ativar o debug das requisições ajax, percebi que o arquivo `/contactform7/lead-conversion.php` não era incluído no hook após o envio do form.

Vendo o arquivo `rdstation-wp.php`, notei que existe uma condição que usa a conditional-tag `is_admin()`, o que é perfeitamente correto ao considerar a inclusão dos arquivos que criam os campos de opções para criar as integrações. No entanto, imagino que essa condição não seja apropriada para o outro arquivo citado, pois após a submissão do form, o include do arquivo necessário para gerar a integração não satisfaz a condição de "estar em uma página da área administrativa".

Movendo o include para fora da condição, a integração funcionou perfeitamente.

Dêem uma checada, e caso eu tenha cometido algum engano (ou esteja utilizando o plugin incorretamente), me dêem um toque aqui!

Abraços

**Comment by filipenasc** [comment]
Olá @augustoms. Você estava certo, realmente ocorreu esse problema, e deixamos passar despercebido na última atualização. Corrigimos o problema e agradecemos a sua colaboração.

Abraço.
